# order expire minutes
expire_minutes: 60
# merchant id
merchant_id: '777290058110836'
# cfca file path
pfx_filepath: pem/PM_700000000000001_acp.pfx
# cfca PEM password
password: '000000'
# x509 cert path
x509_filepath: pem/verify_sign_acp.cer
# digest method
digest_method: sha1
# notify url for back notify from unionpay
backend_url: https://zhouyang.me/unionpay/notify
# unionpay trade address
# app_trans_url: https://101.231.204.80:5000/gateway/api/appTransReq.do
app_trans_url: http://127.0.0.1:8080/
front_trans_url: https://101.231.204.80:5000/gateway/api/frontTransReq.do
back_trans_url: https://101.231.204.80:5000/gateway/api/backTransReq.do
card_back_trade: https://101.231.204.80:5000/gateway/api/cardTransReq.do
single_query_url: https://101.231.204.80:5000/gateway/api/queryTrans.do
batch_trans_url: https://101.231.204.80:5000/gateway/api/batchTrans.do
file_trans_url: https://101.231.204.80:9080/